kind: PersistentVolume
apiVersion: v1
metadata:
  name: scylla-storage-volume
  namespace: subcord
  labels:
    type: local
    app: scylla
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/scylla"
